const $=id=>document.getElementById(id),brl=n=>Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let token=localStorage.getItem('rp_token'),me=null,socket=null,map=null,driverMarker=null,watchId=null,neigh=[];
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};let r=await fetch(url,opt);let j=await r.json().catch(()=>({}));if(r.status===401){logout();throw Error(j.error||'Sessão expirada')}if(!r.ok)throw Error(j.error||'Erro');return j}
function loginView(reg=false){$('app').innerHTML=`<div class="login"><div class="box"><div class="brand">Rota<span>Pro</span> • Entregas</div><h2>${reg?'Cadastro do entregador':'Entrar'}</h2>${reg?'<label>Nome</label><input id="name" class="field" placeholder="Seu nome">':''}<label>Telefone</label><input id="phone" class="field" placeholder="(00) 00000-0000"><label>Senha</label><input id="password" type="password" class="field" placeholder="Senha"><div id="pixFields" class="${reg?'':'hide'}"><label>Tipo da chave Pix</label><select id="pixType" class="field"><option>CPF</option><option>CNPJ</option><option>Telefone</option><option>Email</option><option>Chave aleatória</option></select><label>Chave Pix</label><input id="pixKey" class="field" placeholder="Sua chave Pix"></div><button class="btn primary" style="width:100%;margin-top:15px" onclick="${reg?'register()':'login()'}">${reg?'Criar cadastro':'Entrar'}</button><div class="switch">${reg?'Já tem cadastro?':'É entregador novo?'} <span class="link" onclick="loginView(${!reg})">${reg?'Entrar':'Cadastrar entregador'}</span></div><div id="err" class="danger" style="margin-top:10px"></div></div></div>`}
async function login(){try{let j=await api('/api/auth/login',{method:'POST',body:JSON.stringify({phone:$('phone').value,password:$('password').value})});token=j.token;localStorage.setItem('rp_token',token);boot()}catch(e){$('err').textContent=e.message}}
async function register(){try{let j=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('name').value,phone:$('phone').value,password:$('password').value,pixType:$('pixType').value,pixKey:$('pixKey').value})});token=j.token;localStorage.setItem('rp_token',token);boot()}catch(e){$('err').textContent=e.message}}
function logout(){token=null;localStorage.removeItem('rp_token');if(socket)socket.disconnect();if(watchId!==null)navigator.geolocation.clearWatch(watchId);loginView()}
async function boot(){try{let j=await api('/api/me');me=j.user;socket=io({auth:{token}});socket.on('order:new',o=>{if(me.role==='driver'){notify('Nova entrega disponível',o.client_name+' • '+brl(o.fee));renderDriver()}});socket.on('order:status',()=>renderAll());renderShell();renderAll()}catch(e){loginView()}}
function renderShell(){let admin=me.role==='admin';$('app').innerHTML=`<header><div class="wrap"><div class="topline"><div><div class="brand">Rota<span>Pro</span> • Entregas</div><div class="mini" style="color:#cbd5e1">Olá, ${me.name}</div></div><button class="btn" style="background:#ffffff22;color:#fff" onclick="logout()">Sair</button></div><div class="hero"><div><h1>${admin?'Operação de entregas':'Painel do entregador'}</h1><p>${admin?'Lance pedidos e acompanhe sua equipe.':'Fique disponível e receba novas entregas.'}</p></div><div class="bike">🏍️</div></div></div></header><main><div class="tabs">${admin?'<button onclick="tab(\'buscar\')" id="tb-buscar">🔎 Buscar</button><button onclick="tab(\'clientes\')" id="tb-clientes">👥 Clientes</button><button onclick="tab(\'pedidos\')" id="tb-pedidos">📦 Pedidos</button><button onclick="tab(\'mapa\')" id="tb-mapa">🗺️ Mapa</button>':'<button onclick="tab(\'driver\')" id="tb-driver">🏍️ Entregas</button><button onclick="tab(\'mapa\')" id="tb-mapa">🗺️ Mapa</button><button onclick="tab(\'perfil\')" id="tb-perfil">👤 Perfil</button>'}</div><section id="content"></section></main><div class="bottom"><div>${admin?'<button onclick="tab(\'buscar\')">🔎 Buscar</button><button onclick="tab(\'clientes\')">👥 Clientes</button><button onclick="tab(\'pedidos\')">📦 Pedidos</button><button onclick="tab(\'mapa\')">🗺️ Mapa</button>':'<button onclick="tab(\'driver\')">🏍️ Entregas</button><button onclick="tab(\'mapa\')">🗺️ Mapa</button><button onclick="tab(\'perfil\')">👤 Perfil</button>'}</div></div>`;tab(admin?'buscar':'driver')}
async function renderAll(){if(!me)return;if(me.role==='admin'){if($('tb-pedidos')?.classList.contains('on'))renderAdminOrders();}else{if($('tb-driver')?.classList.contains('on'))renderDriver();}}
function markTab(id){document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('on'));$('tb-'+id)?.classList.add('on')}
function tab(id){markTab(id); if(id==='buscar')renderSearch();if(id==='clientes')renderClients();if(id==='pedidos')renderAdminOrders();if(id==='mapa')renderMap();if(id==='driver')renderDriver();if(id==='perfil')renderProfile()}
async function renderSearch(){let rows=await api('/api/neighborhoods');neigh=rows;$('content').innerHTML=`<div class="card"><input class="search" id="ns" placeholder="Pesquisar bairro ou local..." oninput="filterN()"><div id="nlist"></div></div>`;filterN()}
function filterN(){let q=($('ns')?.value||'').toLowerCase();let r=neigh.filter(x=>x.name.toLowerCase().includes(q));$('nlist').innerHTML=r.map(x=>`<div class="item"><div><b>${x.name}</b><div class="mini">Taxa de entrega</div></div><div class="fee">${brl(x.fee)}</div></div>`).join('')}
async function renderClients(){let rows=await api('/api/clients');let ns=neigh.length?neigh:await api('/api/neighborhoods');neigh=ns;$('content').innerHTML=`<div class="card"><h3>👤 Novo cliente</h3><label>Nome</label><input id="cn" class="field"><label>Telefone</label><input id="cp" class="field"><label>Endereço</label><input id="ca" class="field"><label>Bairro / local</label><select id="cne" class="field">${ns.map(n=>`<option value="${n.id}">${n.name} — ${brl(n.fee)}</option>`).join('')}</select><button class="btn primary" style="margin-top:12px;width:100%" onclick="saveClient()">Salvar cliente</button></div><div class="card"><input class="search" placeholder="Pesquisar cliente..." oninput="filterClients(this.value)"><div id="clist">${clientHTML(rows)}</div></div>`}
function clientHTML(rows){return rows.map(c=>`<div class="item"><div><b>${c.favorite?'⭐ ':''}${c.name}</b><div class="mini">${c.phone||''} • ${c.address} • ${c.neighborhood_name||''}</div></div><button class="btn dark" onclick="useClient(${c.id})">Usar</button></div>`).join('')||'<div class="center">Nenhum cliente salvo.</div>'}
let clientCache=[];async function filterClients(q){clientCache=await api('/api/clients?search='+encodeURIComponent(q));$('clist').innerHTML=clientHTML(clientCache)}
async function saveClient(){try{await api('/api/clients',{method:'POST',body:JSON.stringify({name:$('cn').value,phone:$('cp').value,address:$('ca').value,neighborhoodId:Number($('cne').value)})});renderClients()}catch(e){alert(e.message)}}
function useClient(id){localStorage.setItem('rp_selected_client',id);tab('pedidos')}
async function renderAdminOrders(){let os=await api('/api/orders');let total=os.reduce((s,o)=>s+Number(o.fee),0);$('content').innerHTML=`<div class="stats"><div class="stat"><small>PEDIDOS</small><b>${os.length}</b></div><div class="stat"><small>TAXAS</small><b>${brl(total)}</b></div><div class="stat"><small>PENDENTES</small><b>${os.filter(o=>o.status==='pending').length}</b></div></div><div class="card"><h3>➕ Lançar pedido</h3><label>Cliente</label><input id="oname" class="field" placeholder="Nome do cliente"><label>Endereço</label><input id="oaddr" class="field" placeholder="Rua, número, complemento"><label>Bairro / local</label><select id="oneigh" class="field" onchange="feePreview()">${(neigh.length?neigh:await api('/api/neighborhoods')).map(n=>`<option value="${n.id}" data-fee="${n.fee}">${n.name}</option>`).join('')}</select><div class="mini" id="ofee" style="margin:8px 0;font-weight:900"></div><button class="btn primary" style="width:100%" onclick="createOrder()">📳 Enviar para entregadores</button></div><div>${os.map(o=>`<div class="card"><div class="topline"><b>#${o.id} • ${o.client_name}</b><span class="badge">${o.status}</span></div><div class="mini">${o.neighborhood_name||''} • ${o.address}</div><div style="margin-top:8px;font-weight:900">${brl(o.fee)} ${o.driver_name?'• '+o.driver_name:''}</div></div>`).join('')}</div>`;feePreview()}
function feePreview(){let s=$('oneigh'),n=s.options[s.selectedIndex];$('ofee').textContent='Taxa: '+brl(Number(n.dataset.fee))}
async function createOrder(){try{await api('/api/orders',{method:'POST',body:JSON.stringify({clientName:$('oname').value,address:$('oaddr').value,neighborhoodId:Number($('oneigh').value)})});alert('Pedido enviado! Os entregadores disponíveis receberam o alerta.');renderAdminOrders()}catch(e){alert(e.message)}}
async function renderDriver(){let j=await api('/api/me');let os=await api('/api/orders');let d=j.driver;let pending=os.filter(o=>o.status==='pending');$('content').innerHTML=`<div class="card driverhero"><div class="pulse"></div><b>Disponibilidade</b><div style="margin-top:8px"><button class="btn ${d.available?'green':'dark'}" onclick="setAvailable(${!d.available})">${d.available?'🟢 ONLINE — receber entregas':'⚫ OFFLINE — ficar disponível'}</button></div></div>${pending.map(o=>`<div class="card alert"><div class="topline"><b>🔔 Nova entrega #${o.id}</b><span class="fee">${brl(o.fee)}</span></div><p><b>${o.client_name}</b><br>${o.neighborhood_name||''}<br>${o.address}</p><div class="row"><button class="btn green" onclick="acceptOrder(${o.id})">✅ Aceitar</button><button class="btn red" onclick="rejectOrder(${o.id})">Recusar</button></div></div>`).join('')||'<div class="card center">Nenhuma entrega aguardando você.</div>'}<div class="card"><h3>Minhas entregas</h3>${os.filter(o=>o.status!=='pending').map(o=>`<div class="item"><div><b>#${o.id} • ${o.client_name}</b><div class="mini">${o.neighborhood_name||''} • ${o.address}</div></div><div><span class="badge">${o.status}</span>${['accepted','picked_up'].includes(o.status)?`<button class="btn dark" onclick="navigate(${o.id})">🗺️ Rota</button>`:''}</div></div>`).join('')||'<div class="center">Sem entregas ainda.</div>'}</div>`}
async function setAvailable(v){await api('/api/driver/availability',{method:'PUT',body:JSON.stringify({available:v})});if(v)startGPS();else stopGPS();renderDriver()}
async function acceptOrder(id){try{await api('/api/orders/'+id+'/accept',{method:'POST'});startGPS();renderDriver();tab('mapa')}catch(e){alert(e.message)}}async function rejectOrder(id){try{await api('/api/orders/'+id+'/reject',{method:'POST'});renderDriver()}catch(e){alert(e.message)}}
async function renderProfile(){let j=await api('/api/me'),d=j.driver;$('content').innerHTML=`<div class="card"><h3>👤 ${j.user.name}</h3><div class="mini">${j.user.phone}</div><label>Tipo da chave Pix</label><select id="pt" class="field"><option ${d.pix_type==='CPF'?'selected':''}>CPF</option><option ${d.pix_type==='CNPJ'?'selected':''}>CNPJ</option><option ${d.pix_type==='Telefone'?'selected':''}>Telefone</option><option ${d.pix_type==='Email'?'selected':''}>Email</option><option ${d.pix_type==='Chave aleatória'?'selected':''}>Chave aleatória</option></select><label>Chave Pix</label><input id="pk" class="field" value="${d.pix_key||''}"><button class="btn primary" style="width:100%;margin-top:12px" onclick="savePix()">Salvar Pix</button></div>`}
async function savePix(){await api('/api/driver/profile',{method:'PUT',body:JSON.stringify({pixType:$('pt').value,pixKey:$('pk').value})});alert('Pix atualizado!')}
async function renderMap(){let os=await api('/api/orders');$('content').innerHTML=`<div class="card"><h3>🗺️ Mapa da entrega</h3><p class="mini">No entregador, sua localização é compartilhada enquanto há entrega ativa. No administrador, o mapa recebe a posição do entregador em tempo real.</p><div id="map"></div></div>`;setTimeout(()=>initMap(os),50)}
function initMap(os){if(map)map.remove();map=L.map('map').setView([-11.86,-55.50],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);if(me.role==='driver'&&navigator.geolocation)startGPS();if(me.role==='admin'){api('/api/drivers').then(ds=>ds.filter(d=>d.last_lat&&d.last_lng).forEach(d=>{let m=L.marker([d.last_lat,d.last_lng]).addTo(map).bindPopup('🏍️ '+d.name);}))}}
function navigate(id){api('/api/orders').then(os=>{let o=os.find(x=>x.id===id);if(o)window.open('https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(o.address+', '+o.neighborhood_name),'_blank')})}
function startGPS(){if(watchId!==null||!navigator.geolocation)return;watchId=navigator.geolocation.watchPosition(p=>{api('/api/driver/location',{method:'POST',body:JSON.stringify({lat:p.coords.latitude,lng:p.coords.longitude})}).catch(()=>{});if(map){if(!driverMarker)driverMarker=L.marker([p.coords.latitude,p.coords.longitude]).addTo(map).bindPopup('Você');else driverMarker.setLatLng([p.coords.latitude,p.coords.longitude])}},()=>{}, {enableHighAccuracy:true,maximumAge:5000,timeout:10000})}function stopGPS(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null}
function notify(title,body){try{if(Notification.permission==='granted')new Notification(title,{body});else if(Notification.permission!=='denied')Notification.requestPermission();navigator.vibrate?.([250,100,250])}catch(e){}}
if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();token?boot():loginView();
