require('dotenv').config();
const express=require('express'); const http=require('http'); const cors=require('cors'); const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken'); const {Pool}=require('pg'); const {Server}=require('socket.io');
const fs=require('fs'); const path=require('path');
const app=express(); const server=http.createServer(app); const io=new Server(server,{cors:{origin:true,credentials:true}});
const pool=new Pool(process.env.DATABASE_URL ? {connectionString:process.env.DATABASE_URL, ssl: process.env.PGSSL==='true' ? {rejectUnauthorized:false} : undefined} : {host:process.env.PGHOST, port:Number(process.env.PGPORT||5432), database:process.env.PGDATABASE, user:process.env.PGUSER, password:process.env.PGPASSWORD, ssl:process.env.PGSSL==='true' ? {rejectUnauthorized:false} : undefined});
const PORT=Number(process.env.PORT||3000), SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
app.set('trust proxy', 1);
app.use(cors()); app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
async function q(text,params=[]){return (await pool.query(text,params)).rows}
function token(u){return jwt.sign({id:u.id,name:u.name,role:u.role},SECRET,{expiresIn:'7d'})}
function auth(req,res,next){try{const h=req.headers.authorization||''; req.user=jwt.verify(h.replace('Bearer ','').trim(),SECRET);next()}catch(e){res.status(401).json({error:'Não autenticado'})}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Sem permissão'})}
async function init(){await q(fs.readFileSync(path.join(__dirname,'db/schema.sql'),'utf8')); const seed=fs.readFileSync(path.join(__dirname,'db/seed.sql'),'utf8'); await q(seed);}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'RotaPro'}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,phone,password,role='driver',pixType,pixKey}=req.body;if(!name||!phone||!password)return res.status(400).json({error:'Nome, telefone e senha são obrigatórios'});if(role!=='driver')return res.status(400).json({error:'Cadastro público é somente para entregador'});const hash=await bcrypt.hash(password,12);const u=(await q('INSERT INTO users(name,phone,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,phone,role',[name,phone,hash,'driver']))[0];await q('INSERT INTO drivers(user_id,pix_type,pix_key) VALUES($1,$2,$3)',[u.id,pixType||null,pixKey||null]);res.json({user:u,token:token(u)})}catch(e){res.status(400).json({error:e.code==='23505'?'Telefone já cadastrado':e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const {phone,password}=req.body;const u=(await q('SELECT id,name,phone,password_hash,role FROM users WHERE phone=$1',[phone]))[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Telefone ou senha inválidos'});delete u.password_hash;res.json({user:u,token:token(u)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/me',auth,async(req,res)=>{const u=(await q('SELECT id,name,phone,role FROM users WHERE id=$1',[req.user.id]))[0];let d=null;if(u.role==='driver')d=(await q('SELECT pix_type,pix_key,available,last_lat,last_lng,last_location_at FROM drivers WHERE user_id=$1',[u.id]))[0];res.json({user:u,driver:d})});
app.put('/api/driver/profile',auth,role('driver'),async(req,res)=>{const {pixType,pixKey}=req.body;await q('UPDATE drivers SET pix_type=$1,pix_key=$2 WHERE user_id=$3',[pixType||null,pixKey||null,req.user.id]);res.json({ok:true})});
app.put('/api/driver/availability',auth,role('driver'),async(req,res)=>{const available=!!req.body.available;await q('UPDATE drivers SET available=$1 WHERE user_id=$2',[available,req.user.id]);io.to('admins').emit('driver:availability',{driverId:req.user.id,available});res.json({available})});
app.post('/api/driver/location',auth,role('driver'),async(req,res)=>{const {lat,lng}=req.body;if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'Coordenadas inválidas'});await q('UPDATE drivers SET last_lat=$1,last_lng=$2,last_location_at=NOW() WHERE user_id=$3',[lat,lng,req.user.id]);const active=await q("SELECT id FROM orders WHERE driver_id=$1 AND status IN ('accepted','picked_up') ORDER BY id DESC LIMIT 1",[req.user.id]);if(active[0])io.to('admins').emit('driver:location',{driverId:req.user.id,orderId:active[0].id,lat,lng});res.json({ok:true})});
app.get('/api/neighborhoods',auth,async(req,res)=>{const s=(req.query.search||'').trim();const rows=await q('SELECT id,name,fee FROM neighborhoods WHERE name ILIKE $1 ORDER BY name LIMIT 100',[`%${s}%`]);res.json(rows)});
app.get('/api/clients',auth,async(req,res)=>{const s=(req.query.search||'').trim();res.json(await q('SELECT c.*,n.name neighborhood_name,n.fee FROM clients c LEFT JOIN neighborhoods n ON n.id=c.neighborhood_id WHERE c.name ILIKE $1 OR COALESCE(c.phone,\'\') ILIKE $1 ORDER BY c.favorite DESC,c.name LIMIT 100',[`%${s}%`]))});
app.post('/api/clients',auth,async(req,res)=>{const {name,phone,address,neighborhoodId,favorite=false}=req.body;if(!name||!address)return res.status(400).json({error:'Nome e endereço são obrigatórios'});const c=(await q('INSERT INTO clients(name,phone,address,neighborhood_id,favorite,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,phone||null,address,neighborhoodId||null,!!favorite,req.user.id]))[0];res.json(c)});
app.put('/api/clients/:id',auth,async(req,res)=>{const {name,phone,address,neighborhoodId,favorite}=req.body;const c=(await q('UPDATE clients SET name=COALESCE($1,name),phone=COALESCE($2,phone),address=COALESCE($3,address),neighborhood_id=COALESCE($4,neighborhood_id),favorite=COALESCE($5,favorite) WHERE id=$6 RETURNING *',[name,phone,address,neighborhoodId,favorite,req.params.id]))[0];res.json(c||{})});
app.get('/api/orders',auth,async(req,res)=>{const where=req.user.role==='driver'?'WHERE o.driver_id=$1':'WHERE o.status<>\'cancelled\'';const p=req.user.role==='driver'?[req.user.id]:[];res.json(await q(`SELECT o.*,n.name neighborhood_name,u.name driver_name FROM orders o LEFT JOIN neighborhoods n ON n.id=o.neighborhood_id LEFT JOIN users u ON u.id=o.driver_id ${where} ORDER BY o.created_at DESC LIMIT 200`,p))});
app.post('/api/orders',auth,role('admin'),async(req,res)=>{const {clientId,clientName,address,neighborhoodId}=req.body;const n=(await q('SELECT id,name,fee FROM neighborhoods WHERE id=$1',[neighborhoodId]))[0];if(!clientName||!address||!n)return res.status(400).json({error:'Cliente, endereço e bairro são obrigatórios'});const o=(await q('INSERT INTO orders(client_id,client_name,address,neighborhood_id,fee,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[clientId||null,clientName,address,n.id,n.fee,req.user.id]))[0];io.to('drivers').emit('order:new',o);res.json(o)});
app.post('/api/orders/:id/accept',auth,role('driver'),async(req,res)=>{const o=(await q("UPDATE orders SET driver_id=$1,status='accepted',accepted_at=NOW() WHERE id=$2 AND status='pending' AND driver_id IS NULL RETURNING *",[req.user.id,req.params.id]))[0];if(!o)return res.status(409).json({error:'Essa entrega já foi aceita por outro entregador'});io.to('admins').emit('order:status',o);io.to('driver:'+req.user.id).emit('order:status',o);res.json(o)});
app.post('/api/orders/:id/reject',auth,role('driver'),async(req,res)=>{const o=(await q("UPDATE orders SET status='rejected' WHERE id=$1 AND status='pending' RETURNING *",[req.params.id]))[0];if(!o)return res.status(409).json({error:'Pedido indisponível'});io.to('admins').emit('order:status',o);res.json(o)});
app.post('/api/orders/:id/status',auth,async(req,res)=>{const allowed=['picked_up','delivered','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Status inválido'});const extra=req.body.status==='delivered'?",delivered_at=NOW()":'';const o=(await q(`UPDATE orders SET status=$1 ${extra} WHERE id=$2 ${req.user.role==='driver'?"AND driver_id=$3":''} RETURNING *`,req.user.role==='driver'?[req.body.status,req.params.id,req.user.id]:[req.body.status,req.params.id]))[0];if(!o)return res.status(404).json({error:'Pedido não encontrado'});io.to('admins').emit('order:status',o);if(o.driver_id)io.to('driver:'+o.driver_id).emit('order:status',o);res.json(o)});
app.get('/api/drivers',auth,role('admin'),async(req,res)=>res.json(await q('SELECT u.id,u.name,u.phone,d.pix_type,d.pix_key,d.available,d.last_lat,d.last_lng,d.last_location_at FROM users u JOIN drivers d ON d.user_id=u.id ORDER BY u.name')));
io.use((socket,next)=>{try{socket.user=jwt.verify(socket.handshake.auth?.token,SECRET);next()}catch(e){next(new Error('unauthorized'))}});
io.on('connection',socket=>{if(socket.user.role==='admin')socket.join('admins');if(socket.user.role==='driver'){socket.join('drivers');socket.join('driver:'+socket.user.id)}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log(`RotaPro online na porta ${PORT}`))).catch(e=>{console.error('Falha ao iniciar RotaPro:',e);process.exit(1)});

process.on('SIGTERM',async()=>{await pool.end().catch(()=>{});server.close(()=>process.exit(0))});
process.on('SIGINT',async()=>{await pool.end().catch(()=>{});server.close(()=>process.exit(0))});
